#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Oct 23 17:53:28 2021

@author: lorenzomeloncelli
"""

import requests

res = requests.get("https://api.artic.edu/api/v1/artworks")
file1 =  open("./file-" + "Art-institute-of-chicago" + ".json", "w+")
print(file1)
file1.writelines(res.text)
file1.close()

import json
import pandas

l = []
dati_json = json.load(open("./file-" + "Art-institute-of-chicago" + ".json"))
for h in dati_json["data"]:
    x = list(h.values())
    l.append(x)
        
csv_file_path = 'Art.csv'
df = pandas.DataFrame(l)
name_92 = [i for i in dati_json["data"][0]]
name_93 = [i for i in dati_json["data"][3]]
name_92.insert(88, name_93[88])
df.columns = name_92
df.to_csv(csv_file_path, index=False)

for i in range(92):
    if name_92[i] == name_93[i]:
        pass
    else:
        print(i)
    